import { Music } from "@appTypes/music";
import { HeartBeat } from "@components/custom/HeartBeat";
import { OnTheStage } from "@components/custom/OnTheStage";

export const musics: Music[] = [
  {
    id: 0,
    korTitle: "밤을 달리다",
    enTitle: "Into The Night",
    title: "夜に駆ける",
  },
  {
    id: 1,
    korTitle: "저 꿈을 덧그리며",
    enTitle: "Tracing A Dream",
    title: "あの夢をなぞって",
  },
  {
    id: 2,
    korTitle: "봄망초",
    enTitle: "Halzion",
    title: "ハルジオン",
  },
  {
    id: 3,
    korTitle: "아마도",
    enTitle: "Haven't",
    title: "たぶん",
  },
  {
    id: 4,
    korTitle: "군청",
    enTitle: "Blue",
    title: "群青",
  },
  {
    id: 5,
    korTitle: "하루카",
    enTitle: "Haruka",
    title: "ハルカ",
  },
  {
    id: 6,
    korTitle: "괴물",
    enTitle: "Monster",
    title: "怪物",
  },
  {
    id: 7,
    korTitle: "상냥한 혜성",
    enTitle: "Comet",
    title: "優しい彗星",
  },
  {
    id: 8,
    korTitle: "조금만 더",
    enTitle: "Just a Little Step",
    title: "もう少しだけ",
  },
  {
    id: 9,
    korTitle: "삼원색",
    enTitle: "RGB",
    title: "三原色",
  },
  {
    id: 10,
    korTitle: "앙코르",
    enTitle: "Encore",
    title: "アンコール",
  },
  {
    id: 11,
    korTitle: "러브레터",
    enTitle: "Love Letter",
    title: "ラブレター",
  },
  {
    id: 12,
    korTitle: "다이쇼 로망",
    enTitle: "Romance",
    title: "大正浪漫",
  },
  {
    id: 13,
    korTitle: "제비",
    enTitle: "The Swallow",
    title: "ツバメ",
  },
  {
    id: 14,
    korTitle: "미스터",
    enTitle: "Mister",
    title: "ミスター",
  },
  {
    id: 15,
    korTitle: "좋아해",
    enTitle: "Loving You",
    title: "好きだ",
  },
  {
    id: 16,
    korTitle: "만약에 생명을 그릴 수 있다면",
    enTitle: "If I Could Draw Life",
    title: "もしも命が描けたら",
  },
  {
    id: 17,
    korTitle: "축복",
    enTitle: "The Blessing",
    title: "祝福",
  },
  {
    id: 18,
    korTitle: "바다가 이끄는대로",
    enTitle: "manimani",
    title: "海のまにまに",
  },
  {
    id: 19,
    korTitle: "어드벤처",
    enTitle: "Adventure",
    title: "アドベンチャー",
  },
  {
    id: 20,
    korTitle: "세븐틴",
    enTitle: "Seventeen",
    title: "セブンティーン",
  },
  {
    id: 21,
    korTitle: "아이돌",
    enTitle: "Idol",
    title: "アイドル",
  },
  {
    id: 22,
    korTitle: "용사",
    enTitle: "Brave",
    title: "勇者",
  },
  {
    id: 23,
    korTitle: "Biri-Biri",
    enTitle: "Biri-Biri",
    title: "Biri-Biri",
  },
  {
    id: 24,
    korTitle: "HEART BEAT",
    enTitle: "HEART BEAT",
    title: "HEART BEAT",
    CustomComponent: HeartBeat,
  },
  {
    id: 25,
    korTitle: "UNDEAD",
    enTitle: "UNDEAD",
    title: "UNDEAD",
  },
  {
    id: 26,
    korTitle: "무대에 서서",
    enTitle: "On The Stage",
    title: "舞台に立って",
    CustomComponent: OnTheStage,
  },
  {
    id: 27,
    korTitle: "모노톤",
    enTitle: "Monotone",
    title: "モノトーン",
  },
  {
    id: 28,
    korTitle: "New Me",
    enTitle: "New Me",
    title: "New Me",
  },
];
