export const onTheStageContents: OnTheStage[] = [
  {
    id: 1,
    type: "comic",
    contentId: 1,
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "떨어진 두 사람",
    contentWriter: "타이잔5",
    translator: "DCinside Sink",
    translatorUrl:
      "https://gall.dcinside.com/mgallery/board/view/?id=yoasobi&no=76287",
    originalUrl: "https://shonenjumpplus.com/episode/17106371892389129066",
    length: 66,
  },
  {
    id: 2,
    type: "novel",
    contentId: "27-1",
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "떨어진 두 사람",
    contentWriter: "에사카 준",
    translator: "xooxiuxu",
    translatorUrl: "https://m.blog.naver.com/xooxiuxu/223551799984",
    originalUrl: "https://www.yoasobi-music.jp/novels/hanaretafutari/",
  },
  {
    id: 3,
    type: "comic",
    contentId: 2,
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "Parallel Lane",
    contentWriter: "키리시마 유키",
    translator: "청배무가",
    translatorUrl: "https://m.blog.naver.com/sniperriflesr2/223531115296",
    originalUrl: "https://shonenjumpplus.com/episode/17106371892389129451",
    length: 58,
  },
  {
    id: 2,
    type: "novel",
    contentId: "27-2",
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "Parallel Lane",
    contentWriter: "에사카 준",
    translator: "xooxiuxu",
    translatorUrl: "https://m.blog.naver.com/xooxiuxu/223551800253",
    originalUrl: "https://www.yoasobi-music.jp/novels/parallel-lane/",
  },
  {
    id: 5,
    type: "comic",
    contentId: 3,
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "끝나지 않는 듀스",
    contentWriter: "하루노 히루시타",
    translator: "청배무가",
    translatorUrl: "https://m.blog.naver.com/sniperriflesr2/223532308810",
    originalUrl: "https://shonenjumpplus.com/episode/17106371892389130477",
    length: 55,
  },
  {
    id: 6,
    type: "novel",
    contentId: "27-3",
    title: "舞台に立って",
    korTitle: "무대에 서서",
    contentTitle: "끝나지 않는 듀스",
    contentWriter: "에사카 준",
    translator: "xooxiuxu",
    translatorUrl: "https://m.blog.naver.com/xooxiuxu/223551800729",
    originalUrl: "https://www.yoasobi-music.jp/novels/owaranai-deuce/",
  },
];
