import { Music } from "@appTypes/music";

export const musics: Music[] = [
  {
    id: 1,
    originalNovelUrl: "https://monogatary.com/story/33826",
    korTitle: "밤을 달리다",
    enTitle: "Racing into the Night",
    title: "夜に駆ける",
    novelTitle: "타나토스의 유혹",
    novelWriter: "호시노 마요",
    translated: true,
    isPublished: true,
    translator: "DCinside 서꼬",
  },
  {
    id: 2,
    originalNovelUrl: "https://monogatary.com/story/38869",
    korTitle: "저 꿈을 덧그리며",
    enTitle: "Tracing That Dream",
    title: "あの夢をなぞって",
    novelTitle: "꿈의 물방울과 별의 꽃",
    novelWriter: "이시키 소타",
    translated: true,
    translator: "@prism_translate",
    isPublished: true,
  },
  {
    id: 3,
    originalNovelUrl: "https://ebookstore.sony.jp/title/10498769/",
    korTitle: "봄망초",
    enTitle: "Halzion",
    title: "ハルジオン",
    novelTitle: "그래도 해피엔딩",
    novelWriter: "하시즈메 슌키",
    translated: true,
    isPublished: false,
    translator: "@setoka26",
  },
  {
    id: 4,
    originalNovelUrl: "https://monogatary.com/story/48324",
    korTitle: "아마도",
    enTitle: "Maybe",
    title: "たぶん",
    novelTitle: "아마도",
    novelWriter: "시나노",
    translated: true,
    isPublished: true,
    translator: "@setoka26",
  },
  {
    id: 5,
    originalNovelUrl: "",
    korTitle: "군청",
    enTitle: "Ultramarine",
    title: "群青",
    novelTitle: "푸름을 우리편으로",
    novelWriter: "야마구치 츠바사",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 6,
    originalNovelUrl: "https://monogatary.com/story/109216",
    korTitle: "하루카",
    enTitle: "Haruka",
    title: "ハルカ",
    novelTitle: "달왕자",
    novelWriter: "스즈키 오사무",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 7,
    originalNovelUrl: "https://bst-anime.com/sp/",
    korTitle: "괴물",
    enTitle: "Monster",
    title: "怪物",
    novelTitle: "자신의 가슴속에 자신의 귀를 대고서",
    novelWriter: "이타가키 파루",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 8,
    originalNovelUrl: "https://bst-anime.com/sp/",
    korTitle: "상냥한 혜성",
    enTitle: "Gentle Comet",
    title: "優しい彗星",
    novelTitle: "사자자리 유성우인 채로",
    novelWriter: "이타가키 파루",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 9,
    originalNovelUrl: "https://monogatary.com/story/146439",
    korTitle: "조금만 더",
    enTitle: "Just a Bit More",
    title: "もう少しだけ",
    novelTitle: "돌아간다",
    novelWriter: "치하루",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 10,
    originalNovelUrl: "https://ahamo.com/special/yoasobi/novel/",
    korTitle: "삼원색",
    enTitle: "RGB",
    title: "三原色",
    novelTitle: "RGB",
    novelWriter: "코이카도 유치이로",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 11,
    originalNovelUrl: "https://monogatary.com/story/50040",
    korTitle: "앙코르",
    enTitle: "Encore",
    title: "アンコール",
    novelTitle: "세상의 끝과 작별의 노래",
    novelWriter: "미나카미 카나미",
    translated: true,
    translator: "@prism_translate",
    isPublished: true,
  },
  {
    id: 12,
    originalNovelUrl: "https://www.tfm.co.jp/post/lettersong/pdf/letter.pdf",
    korTitle: "러브레터",
    enTitle: "Love Letter",
    title: "ラブレター",
    novelTitle: "음악에게",
    novelWriter: "하츠네의 편지",
    translated: true,
    translator: "unknown",
    isPublished: false,
  },
  {
    id: 13,
    originalNovelUrl: "https://monogatary.com/story/78167",
    korTitle: "다이쇼 로망",
    enTitle: "Taisho Roman",
    title: "大正浪漫",
    novelTitle: "다이쇼 로맨스",
    novelWriter: "NATSUMI",
    translated: true,
    translator: "@prism_translate",
    isPublished: false,
  },
  {
    id: 14,
    originalNovelUrl: "https://www.nhk.or.jp/irotoridori/song/",
    korTitle: "제비",
    enTitle: "Swallow",
    title: "ツバメ",
    novelTitle: "작은 제비의 커다란 꿈",
    novelWriter: "오토즈키 나나",
    translated: true,
    translator: "DCinside Ys",
    isPublished: false,
  },
  {
    id: 15,
    originalNovelUrl: "",
    korTitle: "미스터",
    enTitle: "Mister",
    title: "ミスター",
    novelTitle: "나만의 소유자",
    novelWriter: "시마모토 리우",
    translated: false,
    isPublished: true,
  },
  {
    id: 16,
    originalNovelUrl: "",
    korTitle: "좋아해",
    enTitle: "I Like You",
    title: "好きだ",
    novelTitle: "빛의 씨앗",
    novelWriter: "모리 에토",
    translated: false,
    isPublished: true,
  },
  {
    id: 17,
    originalNovelUrl:
      "https://www.yoasobi-music.jp/novels/moshimoinochigaegaketara/",
    korTitle: "만약에 생명을 그릴 수 있다면",
    enTitle: "If I Could Draw Life",
    title: "もしも命が描けたら",
    novelTitle: "만약에 생명을 그릴 수 있다면",
    novelWriter: "스즈키 오사무",
    translated: false,
    isPublished: false,
  },
  {
    id: 18,
    originalNovelUrl: "https://g-witch.net/music/novel/",
    korTitle: "축복",
    enTitle: "The Blessing",
    title: "祝福",
    novelTitle: "요람의 별",
    novelWriter: "오코우치 이치로",
    translated: true,
    translator: "DCinside Irochi",
    isPublished: false,
  },
  {
    id: 19,
    originalNovelUrl: "",
    korTitle: "바다가 이끄는대로",
    enTitle: "As the Sea Leads",
    title: "海のまにまに",
    novelTitle: "유령",
    novelWriter: "츠지무라 미즈키",
    translated: false,
    isPublished: true,
  },
  {
    id: 20,
    originalNovelUrl: "https://www.usj.co.jp/web/ja/jp/news/2022/1012",
    korTitle: "어드벤처",
    enTitle: "Adventure",
    title: "アドベンチャー",
    novelTitle: "렌즈 너머의 반짝임을",
    novelWriter: "나기",
    translated: true,
    translator: "DCinside 미니미",
    isPublished: false,
  },
  {
    id: 21,
    originalNovelUrl: "",
    korTitle: "세븐틴",
    enTitle: "Seventeen",
    title: "セブンティーン",
    novelTitle: "색이 다른 트럼프",
    novelWriter: "미야베 미유키",
    translated: false,
    isPublished: true,
  },
  {
    id: 22,
    originalNovelUrl: "https://youngjump.jp/oshinoko/novel_45510/novel_01.html",
    korTitle: "아이돌",
    enTitle: "Idol",
    title: "アイドル",
    novelTitle: "45510",
    novelWriter: "아카사카 아카",
    translated: true,
    translator: "DCinside Irochi",
    isPublished: false,
  },
  {
    id: 23,
    originalNovelUrl: "https://frieren-anime.jp/special/novel/",
    korTitle: "용사",
    enTitle: "Brave",
    title: "勇者",
    novelTitle: "주송",
    novelWriter: "키소 지로 / 야마다 카네히토",
    translated: true,
    translator: "DCinside ㅇㅇ",
    isPublished: false,
  },
  {
    id: 24,
    originalNovelUrl: "https://novel-kimiame.pokemon.co.jp/",
    korTitle: "Biri-Biri",
    enTitle: "Biri-Biri",
    title: "Biri-Biri",
    novelTitle: "너와 비를 피하며",
    novelWriter: "다케다 아야노",
    translated: true,
    translator: "키리야아오이, 기그그그",
    isPublished: false,
  },
  {
    id: 25,
    originalNovelUrl: "https://www.nhk.or.jp/18fes/shinon1000/movie/song/",
    korTitle: "HEART BEAT",
    enTitle: "HEART BEAT",
    title: "HEART BEAT",
    novelTitle: "",
    novelWriter: "",
    translated: false,
    isPublished: false,
  },
  {
    id: 26,
    originalNovelUrl:
      "https://www.monogatari-series.com/oms/special/novel/nadeko_past",
    korTitle: "UNDEAD",
    enTitle: "UNDEAD",
    title: "UNDEAD",
    novelTitle: "나데코 페스트, 시노부 퓨처",
    novelWriter: "니시오 이신",
    translated: true,
    translator: "maiden",
    isPublished: false,
  },
  {
    id: 27,
    originalNovelUrl: "",
    korTitle: "무대에 서서",
    enTitle: "Standing on Stage",
    title: "舞台に立って",
    novelTitle: "",
    novelWriter: "",
    translated: false,
    isPublished: false,
  },
  {
    id: 28,
    originalNovelUrl: "https://fureru-movie.com/special/novel/",
    korTitle: "모노톤",
    enTitle: "Monotone",
    title: "モノトーン",
    novelTitle: "후레루。 의, 전야。",
    novelWriter: "오카다 마리",
    translated: false,
    isPublished: false,
  },
  {
    id: 29,
    originalNovelUrl: "https://monogatary.com/story/454872",
    korTitle: "New Me",
    enTitle: "New Me",
    title: "New Me",
    novelTitle: "백산도로 불꽃 사건",
    novelWriter: "아리테 마도",
    translated: false,
    isPublished: false,
  },
];
