import { Music } from "@appTypes/music";
export const musics: Music[] = [
  {
    korTitle: "밤을 달리다",
    title: "夜に駆ける",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "저 꿈을 덧그리며",
    title: "あの夢をなぞって",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "봄망초",
    title: "ハルジオン",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "아마도",
    title: "たぶん",
    translated: false,
    isPublished: false,
  },
  { korTitle: "군청", title: "群青", translated: false, isPublished: false },
  {
    korTitle: "하루카",
    title: "ハルカ",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "앙코르",
    title: "アンコール",
    translated: false,
    isPublished: false,
  },
  { korTitle: "괴물", title: "怪物", translated: false, isPublished: false },
  {
    korTitle: "상냥한 혜성",
    title: "優しい彗星",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "조금만 더",
    title: "もう少しだけ",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "삼원색",
    title: "三原色",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "러브레터",
    title: "ラブレター",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "다이쇼 로망",
    title: "大正浪漫",
    translated: false,
    isPublished: false,
  },
  { korTitle: "제비", title: "ツバメ", translated: false, isPublished: false },
  {
    korTitle: "만약에 생명을 그릴 수 있다면",
    title: "もしも命が描けたら",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "미스터",
    title: "ミスター",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "좋아해",
    title: "好きだ",
    translated: false,
    isPublished: false,
  },
  { korTitle: "축복", title: "祝福", translated: false, isPublished: false },
  {
    korTitle: "바다가 이끄는대로",
    title: "海のまにまに",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "어드밴처",
    title: "アドベンチャー",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "세븐틴",
    title: "セブンティーン",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "아이돌",
    title: "アイドル",
    translated: false,
    isPublished: false,
  },
  { korTitle: "용사", title: "勇者", translated: false, isPublished: false },
  {
    korTitle: "찌릿찌릿",
    title: "BiriBiri",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "하트비트",
    title: "HeartBeat",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "언데드",
    title: "UNDEAD",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "무대에 서서",
    title: "舞台に立って",
    translated: false,
    isPublished: false,
  },
  {
    korTitle: "모노톤",
    title: "モノトーン",
    translated: false,
    isPublished: false,
  },
];
